# Generated by Django 2.1.7 on 2020-01-07 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detailsmodel',
            name='username',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
